# Generated by Django 3.1 on 2020-08-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('cat', models.CharField(choices=[('hoax', 'hoax'), ('valid', 'valid')], max_length=50)),
                ('berita', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermUnikValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_unik', models.CharField(max_length=150)),
                ('valid', models.FloatField()),
                ('hoax', models.FloatField()),
            ],
        ),
    ]
